from django import forms
from .models import CustomUser, Message, Conversation # <-- ADDED 'Message' IMPORT

class GroupConversationForm(forms.ModelForm):
    participants = forms.ModelMultipleChoiceField(
        queryset=CustomUser.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta:
        model = Conversation
        fields = ['name', 'participants']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['participants'].queryset = CustomUser.objects.exclude(id=user.id)

class ProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            "avatar",
            "bio",
            "sustainability_interests",
            "nickname",
        ]
        widgets = {
            "bio": forms.Textarea(attrs={"rows": 4}),
            "sustainability_interests": forms.TextInput(),
            "nickname": forms.TextInput(),
        }
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content', 'image_attachment']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Type your message...'})
        }
        labels = {
            'content': '',
            'image_attachment': 'Attach Image'
        }

SPECIES_CHOICES = [
    ("", "Please select an option"),

    # Maples
    ("sugar_maple", "Sugar Maple"),
    ("red_maple", "Red Maple"),
    ("silver_maple", "Silver Maple"),
    ("norway_maple", "Norway Maple"),
    ("japanese_maple", "Japanese Maple"),
    ("paperbark_maple", "Paperbark Maple"),
    ("amur_maple", "Amur Maple"),
    ("bigleaf_maple", "Bigleaf Maple"),
    ("black_maple", "Black Maple"),
    ("mountain_maple", "Mountain Maple"),
    ("field_maple", "Field Maple"),
    ("tatarian_maple", "Tatarian Maple"),
    ("vine_maple", "Vine Maple"),
    ("hedge_maple", "Hedge Maple"),
    ("striped_maple", "Striped Maple"),
    ("boxelder_maple", "Boxelder"),
    ("hornbeam_maple", "Hornbeam Maple"),
    ("rock_maple", "Rock Maple"),
    ("manitoba_maple", "Manitoba Maple"),
    ("korean_maple", "Korean Maple"),

    # Oaks
    ("white_oak", "White Oak"),
    ("northern_red_oak", "Northern Red Oak"),
    ("southern_red_oak", "Southern Red Oak"),
    ("black_oak", "Black Oak"),
    ("pin_oak", "Pin Oak"),
    ("scarlet_oak", "Scarlet Oak"),
    ("chestnut_oak", "Chestnut Oak"),
    ("bur_oak", "Bur Oak"),
    ("swamp_white_oak", "Swamp White Oak"),
    ("willow_oak", "Willow Oak"),
    ("post_oak", "Post Oak"),
    ("chinkapin_oak", "Chinkapin Oak"),
    ("live_oak", "Live Oak"),
    ("overcup_oak", "Overcup Oak"),
    ("nuttall_oak", "Nuttall Oak"),
    ("shumard_oak", "Shumard Oak"),
    ("laurel_oak", "Laurel Oak"),
    ("water_oak", "Water Oak"),
    ("turkey_oak", "Turkey Oak"),
    ("holly_oak", "Holly Oak"),
    ("holm_oak", "Holm Oak"),
    ("english_oak", "English Oak"),
    ("sessile_oak", "Sessile Oak"),
    ("cork_oak", "Cork Oak"),
    ("portuguese_oak", "Portuguese Oak"),
    ("pyrenean_oak", "Pyrenean Oak"),
    ("japanese_white_oak", "Japanese White Oak"),
    ("sawtooth_oak", "Sawtooth Oak"),
    ("dawn_oak", "Dawn Oak"),  # ornamental

    # Pines
    ("eastern_white_pine", "Eastern White Pine"),
    ("scots_pine", "Scots Pine"),
    ("ponderosa_pine", "Ponderosa Pine"),
    ("lodgepole_pine", "Lodgepole Pine"),
    ("pitch_pine", "Pitch Pine"),
    ("red_pine", "Red Pine"),
    ("jack_pine", "Jack Pine"),
    ("longleaf_pine", "Longleaf Pine"),
    ("shortleaf_pine", "Shortleaf Pine"),
    ("loblolly_pine", "Loblolly Pine"),
    ("slash_pine", "Slash Pine"),
    ("austrian_pine", "Austrian Pine"),
    ("maritime_pine", "Maritime Pine"),
    ("mugo_pine", "Mugo Pine"),
    ("monterey_pine", "Monterey Pine"),
    ("bristlecone_pine", "Bristlecone Pine"),
    ("sugar_pine", "Sugar Pine"),
    ("limber_pine", "Limber Pine"),
    ("whitebark_pine", "Whitebark Pine"),
    ("stone_pine", "Stone Pine"),
    ("japanese_black_pine", "Japanese Black Pine"),
    ("japanese_red_pine", "Japanese Red Pine"),
    ("canary_island_pine", "Canary Island Pine"),
    ("bengal_pine", "Bengal Pine"),
    ("himalayan_pine", "Himalayan Pine"),

    # Spruces
    ("norway_spruce", "Norway Spruce"),
    ("white_spruce", "White Spruce"),
    ("black_spruce", "Black Spruce"),
    ("blue_spruce", "Colorado Blue Spruce"),
    ("sitka_spruce", "Sitka Spruce"),
    ("englemann_spruce", "Engelmann Spruce"),
    ("serbian_spruce", "Serbian Spruce"),
    ("omorika_spruce", "Omorika Spruce"),
    ("oriental_spruce", "Oriental Spruce"),
    ("korean_spruce", "Korean Spruce"),
    ("brewer_spruce", "Brewer Spruce"),
    ("red_spruce", "Red Spruce"),
    ("mexican_spruce", "Mexican Spruce"),

    # Firs / Douglas-fir / Hemlock
    ("balsam_fir", "Balsam Fir"),
    ("fraser_fir", "Fraser Fir"),
    ("noble_fir", "Noble Fir"),
    ("grand_fir", "Grand Fir"),
    ("pacific_silver_fir", "Pacific Silver Fir"),
    ("european_silver_fir", "European Silver Fir"),
    ("canaan_fir", "Canaan Fir"),
    ("concolor_fir", "White Fir"),
    ("douglas_fir", "Douglas-fir"),
    ("japanese_fir", "Japanese Fir"),
    ("nordmann_fir", "Nordmann Fir"),
    ("hemlock_eastern", "Eastern Hemlock"),
    ("hemlock_western", "Western Hemlock"),
    ("carolina_hemlock", "Carolina Hemlock"),

    # Cedars, Cypresses, Junipers, Yews
    ("atlas_cedar", "Atlas Cedar"),
    ("deodar_cedar", "Deodar Cedar"),
    ("lebanon_cedar", "Cedar of Lebanon"),
    ("eastern_red_cedar", "Eastern Red Cedar"),
    ("western_redcedar", "Western Redcedar"),
    ("northern_white_cedar", "Northern White Cedar"),
    ("arizona_cypress", "Arizona Cypress"),
    ("monterey_cypress", "Monterey Cypress"),
    ("italian_cypress", "Italian Cypress"),
    ("bald_cypress", "Bald Cypress"),
    ("pond_cypress", "Pond Cypress"),
    ("lawson_cypress", "Lawson Cypress"),
    ("thuja_green_giant", "Green Giant Arborvitae"),
    ("common_juniper", "Common Juniper"),
    ("rocky_mountain_juniper", "Rocky Mountain Juniper"),
    ("sargent_juniper", "Sargent Juniper"),
    ("japanese_cryptomeria", "Japanese Cedar (Cryptomeria)"),
    ("japanese_yew", "Japanese Yew"),
    ("english_yew", "English Yew"),
    ("pacific_yew", "Pacific Yew"),

    # Birches, Alders
    ("paper_birch", "Paper Birch"),
    ("silver_birch", "Silver Birch"),
    ("river_birch", "River Birch"),
    ("yellow_birch", "Yellow Birch"),
    ("gray_birch", "Gray Birch"),
    ("downy_birch", "Downy Birch"),
    ("himalayan_birch", "Himalayan Birch"),
    ("copper_birch", "Copper Birch"),
    ("swamp_birch", "Swamp Birch"),
    ("alder_black", "Black Alder"),
    ("alder_gray", "Gray Alder"),
    ("alder_red", "Red Alder"),
    ("alder_white", "White Alder"),
    ("alder_green", "Green Alder"),

    # Willows, Poplars, Aspens, Cottonwoods
    ("weeping_willow", "Weeping Willow"),
    ("black_willow", "Black Willow"),
    ("white_willow", "White Willow"),
    ("crack_willow", "Crack Willow"),
    ("goat_willow", "Goat Willow"),
    ("peachleaf_willow", "Peachleaf Willow"),
    ("laurel_willow", "Laurel Willow"),
    ("golden_willow", "Golden Willow"),
    ("corkscrew_willow", "Corkscrew Willow"),
    ("basket_willow", "Basket Willow"),
    ("lombardy_poplar", "Lombardy Poplar"),
    ("black_poplar", "Black Poplar"),
    ("white_poplar", "White Poplar"),
    ("gray_poplar", "Gray Poplar"),
    ("hybrid_poplar", "Hybrid Poplar"),
    ("eastern_cottonwood", "Eastern Cottonwood"),
    ("plains_cottonwood", "Plains Cottonwood"),
    ("fremont_cottonwood", "Fremont Cottonwood"),
    ("narrowleaf_cottonwood", "Narrowleaf Cottonwood"),
    ("quaking_aspen", "Quaking Aspen"),
    ("bigtooth_aspen", "Bigtooth Aspen"),
    ("european_aspen", "European Aspen"),

    # Elms
    ("american_elm", "American Elm"),
    ("slippery_elm", "Slippery Elm"),
    ("rock_elm", "Rock Elm"),
    ("winged_elm", "Winged Elm"),
    ("siberian_elm", "Siberian Elm"),
    ("english_elm", "English Elm"),
    ("wych_elm", "Wych Elm"),
    ("dutch_elm", "Dutch Elm"),
    ("cedar_elm", "Cedar Elm"),
    ("camperdown_elm", "Camperdown Elm"),

    # Ashes
    ("white_ash", "White Ash"),
    ("green_ash", "Green Ash"),
    ("black_ash", "Black Ash"),
    ("blue_ash", "Blue Ash"),
    ("european_ash", "European Ash"),
    ("oregon_ash", "Oregon Ash"),
    ("mountain_ash", "Mountain Ash (Rowan)"),
    ("chinese_ash", "Chinese Ash"),
    ("manna_ash", "Manna Ash"),

    # Beeches, Hornbeams, Lindens
    ("american_beech", "American Beech"),
    ("european_beech", "European Beech"),
    ("copper_beech", "Copper Beech"),
    ("weeping_beech", "Weeping Beech"),
    ("japanese_beech", "Japanese Beech"),
    ("hornbeam_american", "American Hornbeam"),
    ("hornbeam_european", "European Hornbeam"),
    ("ironwood", "Eastern Hophornbeam"),
    ("american_basswood", "American Basswood"),
    ("littleleaf_linden", "Littleleaf Linden"),
    ("silver_linden", "Silver Linden"),
    ("european_linden", "European Linden"),
    ("mongolian_linden", "Mongolian Linden"),

    # Hickories, Walnuts, Pecans
    ("shagbark_hickory", "Shagbark Hickory"),
    ("pignut_hickory", "Pignut Hickory"),
    ("mockernut_hickory", "Mockernut Hickory"),
    ("bitternut_hickory", "Bitternut Hickory"),
    ("shellbark_hickory", "Shellbark Hickory"),
    ("sand_hickory", "Sand Hickory"),
    ("black_walnut", "Black Walnut"),
    ("english_walnut", "English Walnut"),
    ("butternut", "Butternut"),
    ("heartnut", "Heartnut"),
    ("northern_pecan", "Northern Pecan"),
    ("southern_pecan", "Southern Pecan"),
    ("hican", "Hican"),
    ("manchurian_walnut", "Manchurian Walnut"),

    # Cherries, Plums, Peaches, Almonds
    ("black_cherry", "Black Cherry"),
    ("pin_cherry", "Pin Cherry"),
    ("chokecherry", "Chokecherry"),
    ("sweet_cherry", "Sweet Cherry"),
    ("sour_cherry", "Sour Cherry"),
    ("flowering_cherry", "Flowering Cherry"),
    ("yoshino_cherry", "Yoshino Cherry"),
    ("kwanzan_cherry", "Kwanzan Cherry"),
    ("plum_european", "European Plum"),
    ("american_plum", "American Plum"),
    ("chinese_plum", "Chinese Plum"),
    ("purpleleaf_plum", "Purpleleaf Plum"),
    ("apricot", "Apricot"),
    ("peach", "Peach"),
    ("nectarine", "Nectarine"),
    ("almond", "Almond"),

    # Apples & Crabapples, Pears
    ("domestic_apple", "Apple"),
    ("crabapple_sargent", "Sargent Crabapple"),
    ("crabapple_siberian", "Siberian Crabapple"),
    ("crabapple_dolgo", "Dolgo Crabapple"),
    ("crabapple_prairie_fire", "Prairie Fire Crabapple"),
    ("crabapple_snowdrift", "Snowdrift Crabapple"),
    ("callery_pear", "Callery Pear"),
    ("bradford_pear", "Bradford Pear"),
    ("common_pear", "Common Pear"),
    ("korean_pear", "Korean Pear"),

    # Magnolias, Dogwoods, Redbuds, Hawthorns, Serviceberries
    ("southern_magnolia", "Southern Magnolia"),
    ("star_magnolia", "Star Magnolia"),
    ("saucer_magnolia", "Saucer Magnolia"),
    ("cucumber_magnolia", "Cucumber Magnolia"),
    ("sweetbay_magnolia", "Sweetbay Magnolia"),
    ("bigleaf_magnolia", "Bigleaf Magnolia"),
    ("flowering_dogwood", "Flowering Dogwood"),
    ("kousa_dogwood", "Kousa Dogwood"),
    ("pacific_dogwood", "Pacific Dogwood"),
    ("cornelian_cherry_dogwood", "Cornelian Cherry Dogwood"),
    ("eastern_redbud", "Eastern Redbud"),
    ("cercis_chinensis", "Chinese Redbud"),
    ("cercis_canadensis_forest_pansy", "Forest Pansy Redbud"),
    ("washington_hawthorn", "Washington Hawthorn"),
    ("downy_hawthorn", "Downy Hawthorn"),
    ("midland_hawthorn", "Midland Hawthorn"),
    ("cockspur_hawthorn", "Cockspur Hawthorn"),
    ("winter_king_hawthorn", "Winter King Hawthorn"),
    ("downy_serviceberry", "Downy Serviceberry"),
    ("allegheny_serviceberry", "Allegheny Serviceberry"),
    ("shadbush_serviceberry", "Shadbush Serviceberry"),

    # Sycamores / Planes, Hackberries, Sweetgum, Tulip Tree
    ("american_sycamore", "American Sycamore"),
    ("london_plane", "London Plane Tree"),
    ("oriental_plane", "Oriental Plane"),
    ("arizona_sycamore", "Arizona Sycamore"),
    ("hackberry_common", "Common Hackberry"),
    ("hackberry_nettle", "Nettle Tree (Hackberry)"),
    ("sugarberry", "Sugarberry"),
    ("sweetgum", "Sweetgum"),
    ("tulip_tree", "Tulip Poplar / Tulip Tree"),
    ("american_holly", "American Holly"),

    # Locusts, Katsura, Honeylocust, Laburnum
    ("black_locust", "Black Locust"),
    ("honeylocust", "Honeylocust"),
    ("thornless_honeylocust", "Thornless Honeylocust"),
    ("locust_pink", "Pink Locust"),
    ("locust_twig", "Twisty Baby Locust"),
    ("katsura_tree", "Katsura Tree"),
    ("golden_chain_tree", "Golden Chain Tree"),
    ("yellowwood", "Yellowwood"),
    ("redwood_dawn", "Dawn Redwood"),
    ("redwood_coast", "Coast Redwood"),
    ("giant_sequoia", "Giant Sequoia"),

    # Eucalyptus, Acacia, Casuarina etc.
    ("eucalyptus_globulus", "Blue Gum Eucalyptus"),
    ("eucalyptus_regnans", "Mountain Ash Eucalyptus"),
    ("eucalyptus_camaldulensis", "River Red Gum"),
    ("eucalyptus_citriodora", "Lemon-scented Gum"),
    ("eucalyptus_pauciflora", "Snow Gum"),
    ("eucalyptus_viminalis", "Manna Gum"),
    ("eucalyptus_melliodora", "Yellow Box"),
    ("eucalyptus_sideroxylon", "Red Ironbark"),
    ("eucalyptus_pilularis", "Blackbutt"),
    ("eucalyptus_marginata", "Jarrah"),
    ("acacia_dealbata", "Silver Wattle"),
    ("acacia_baileyana", "Cootamundra Wattle"),
    ("acacia_melanoxylon", "Blackwood Acacia"),
    ("acacia_longifolia", "Sydney Golden Wattle"),
    ("acacia_aneura", "Mulga"),
    ("casuarina_equisetifolia", "Beach Sheoak"),
    ("casuarina_cunninghamiana", "River Sheoak"),
    ("casuarina_stricta", "Drooping Sheoak"),
    ("melaleuca_quinquenervia", "Paperbark Melaleuca"),
    ("callistemon_viminalis", "Weeping Bottlebrush"),

    # Tropical / Subtropical fruit & ornamentals
    ("mango", "Mango"),
    ("lychee", "Lychee"),
    ("longan", "Longan"),
    ("jackfruit", "Jackfruit"),
    ("breadfruit", "Breadfruit"),
    ("starfruit", "Starfruit"),
    ("guava", "Guava"),
    ("sapodilla", "Sapodilla"),
    ("tamarind", "Tamarind"),
    ("avocado", "Avocado"),
    ("banana_tree", "Banana (Tree-like)"),
    ("papaya", "Papaya"),
    ("cacao", "Cacao"),
    ("coffee_tree", "Coffee Tree"),
    ("durian", "Durian"),
    ("rambutan", "Rambutan"),
    ("custard_apple", "Custard Apple"),
    ("soursop", "Soursop"),
    ("persimmon_american", "American Persimmon"),
    ("persimmon_asian", "Asian Persimmon"),

    # Tropical hardwoods & others
    ("teak", "Teak"),
    ("mahogany_honduran", "Honduran Mahogany"),
    ("mahogany_african", "African Mahogany"),
    ("rosewood_indian", "Indian Rosewood"),
    ("rosewood_brazilian", "Brazilian Rosewood"),
    ("ipe", "Ipe (Brazilian Walnut)"),
    ("jatoba", "Jatoba"),
    ("zebrano", "Zebrawood"),
    ("wenge", "Wenge"),
    ("ebony_african", "African Ebony"),
    ("sapele", "Sapele"),
    ("meranti", "Meranti"),
    ("kapok_tree", "Kapok Tree"),
    ("ceiba_pentandra", "Silk Cotton Tree"),
    ("rain_tree", "Rain Tree"),
    ("flame_tree", "Flame Tree"),
    ("frangipani", "Frangipani"),
    ("cassia_fistula", "Golden Shower Tree"),

    # Palms
    ("coconut_palm", "Coconut Palm"),
    ("date_palm", "Date Palm"),
    ("canary_island_date_palm", "Canary Island Date Palm"),
    ("oil_palm", "Oil Palm"),
    ("areca_palm", "Areca Palm"),
    ("bismarck_palm", "Bismarck Palm"),
    ("fan_palm", "Fan Palm"),
    ("washingtonia_robusta", "Mexican Fan Palm"),
    ("washingtonia_filifera", "California Fan Palm"),
    ("queen_palm", "Queen Palm"),
    ("king_palm", "King Palm"),
    ("sabal_palmetto", "Cabbage Palmetto"),
    ("sago_palm", "Sago Palm"),
    ("pindo_palm", "Pindo Palm"),
    ("foxtail_palm", "Foxtail Palm"),

    # African trees
    ("baobab_african", "African Baobab"),
    ("marula", "Marula"),
    ("fever_tree", "Fever Tree"),
    ("camelthorn", "Camel Thorn"),
    ("mopane", "Mopane"),
    ("leadwood", "Leadwood"),
    ("tamboti", "Tamboti"),
    ("shepherd_tree", "Shepherd Tree"),
    ("yellowwood_african", "African Yellowwood"),
    ("wattle_black", "Black Wattle"),

    # South American trees
    ("pau_brasil", "Brazilwood (Pau-Brasil)"),
    ("jacaranda_mimosifolia", "Jacaranda"),
    ("tipuana_tipu", "Tipu Tree"),
    ("pau_rosa", "Rosewood Amazonian"),
    ("monkey_puzzle", "Monkey Puzzle Tree"),
    ("parana_pine", "Paraná Pine"),
    ("yerba_mate", "Yerba Mate Tree"),
    ("ceibo", "Ceibo (Coral Tree)"),
    ("queule", "Queule"),
    ("lapacho", "Pink Lapacho"),

    # Mediterranean & ornamental
    ("olive_tree", "Olive"),
    ("cork_oak_mediterranean", "Mediterranean Cork Oak"),
    ("stone_pine_mediterranean", "Mediterranean Stone Pine"),
    ("carob_tree", "Carob"),
    ("bay_laurel", "Bay Laurel"),
    ("medlar", "Medlar"),
    ("pomegranate", "Pomegranate"),
    ("fig_common", "Common Fig"),
    ("fig_sacred", "Sacred Fig"),
    ("cercis_siliquastrum", "Judas Tree"),

    # Misc ornamental / shade trees
    ("ginkgo", "Ginkgo"),
    ("london_plane_tree", "London Plane"),
    ("paulownia", "Empress Tree (Paulownia)"),
    ("austrian_black_pine", "Austrian Black Pine"),
    ("smoke_tree", "Smoke Tree"),
    ("golden_rain_tree", "Golden Rain Tree"),
    ("silver_lace_tree", "Silver Lace Tree"),
    ("silk_tree", "Silk Tree (Mimosa)"),
    ("lilac_tree", "Japanese Tree Lilac"),
    ("stewartia", "Stewartia"),
    ("southern_live_oak", "Southern Live Oak"),
    ("arbutus", "Strawberry Tree"),
]