# Generated by Django 5.2.7 on 2025-11-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sustainability_interests",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
