# Generated by Django 5.2.7 on 2025-11-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_customuser_bio_customuser_sustainability_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
