# Generated by Django 5.2.7 on 2025-12-02 20:22

import django.db.models.deletion
import home.models
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models

def clear_avatars(apps, schema_editor):
    User = apps.get_model("home", "CustomUser")
    User.objects.update(avatar=None)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=home.models.custom_image_path)),
                ('category', models.CharField(choices=[('avatars', 'Avatar'), ('message_attachments', 'Attachment'), ('trees', 'Tree')], max_length=30)),
                ('private', models.BooleanField(default=False)),
                ('flaged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customimage'),
        ),
        migrations.RunPython(clear_avatars)
    ]
