# Generated by Django 5.2.7 on 2025-12-09 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treesubmission',
            name='status',
        ),
        migrations.AddField(
            model_name='treesubmission',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treesubmission',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treesubmission',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_trees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treesubmission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treesubmission',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
