# Generated by Django 5.2.7 on 2025-12-04 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_conversation_admin_conversation_is_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read_by",
            field=models.ManyToManyField(
                blank=True, related_name="read_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
