# Generated by Django 5.2.7 on 2025-12-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_message_read_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
