# Generated by Django 5.2.7 on 2025-12-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customimage_alter_customuser_avatar'),
        ('home', '0006_message_read_by'),
    ]

    operations = [
    ]
