# Generated by Django 5.2.7 on 2025-12-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_treesubmission_status_and_more'),
        ('home', '0007_customuser_profile_completed'),
    ]

    operations = [
    ]
