# Generated by Django 5.2.7 on 2025-12-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20251208_1703'),
        ('home', '0009_notification'),
    ]

    operations = [
    ]
