# Generated by Django 5.2.7 on 2025-12-09 18:19

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="treesubmission",
            name="diameter",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treesubmission",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treesubmission",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="tree_images/",
            ),
        ),
    ]
