# Generated by Django 5.2.7 on 2025-12-09 20:51

import django.db.models.deletion
from django.db import migrations, models

def clear_message_images(apps, schema_editor):
    Message = apps.get_model("home", "Message")
    Message.objects.update(image_attachment=None)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_0007_merge_20251208_1703_0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image_attachment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customimage'),
        ),
        migrations.RunPython(clear_message_images)
    ]
