# Generated by Django 5.2.7 on 2025-12-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_treesubmission_diameter_treesubmission_height_and_more'),
        ('home', '0011_alter_message_image_attachment'),
    ]

    operations = [
    ]
