# Generated by Django 5.2.7 on 2025-12-10 01:42

import django.db.models.deletion
from django.db import migrations, models

def clear_tree_images(apps, schema_editor):
    TreeSubmission = apps.get_model("home", "TreeSubmission")
    TreeSubmission.objects.update(image=None)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_merge_20251209_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='category',
            field=models.CharField(choices=[('avatars', 'Avatar'), ('message_attachments', 'Attachment'), ('tree_images', 'Tree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='treesubmission',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customimage'),
        ),
        migrations.RunPython(clear_tree_images)
    ]
